#! /usr/bin/env python
from fe_utils import *
from math import sin, pi

# m = UnitSquareMesh(2, 2)
m = LShapedRecMesh(2, 2)
# m = LShapedMesh(4, 4)

# fe = LagrangeElement(ReferenceTriangle, 2)
fe = LagrangeElement(ReferenceRectangle, 1)

fs =  FunctionSpace(m, fe)

f = Function(fs)

f.interpolate(lambda x: sin(2*pi*x[0])*sin(2*pi*x[1]))

f.plot()
